config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'users#new', :as => 'register'

  get '/confirm_email/:token', to: 'email_confirmations#confirm', as: 'confirm_email'

  root 'pages#index'

  resources :users
  resources :pages
  resources :candidates
  resources :jobs do
    resources :candidate_jobs, except: %i(index show) do
    end
  end
  resources :admins
  resource  :help, only: %i(show)

  get '/candidate_jobs', controller: :candidate_jobs, action: :index
  get '/candidate_jobs/show/:job_id' => 'candidate_jobs#show', :as => :show_requests
  get '/jobs/calendars/show', as: 'calendar'
end

app/views/admins/index.html.erb
<div class="admin index">
  <h2><%= t('shared.all.welcome') %><%= ' ' %><%= current_user.first_name %> <%= current_user.last_name %></h2>
  <br /><br/>
  <div class="card-deck">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to t('candidate.view_candidates'), candidates_path %></h5>
        <p class="card-text"><%=  t('candidate.view_candidates_desc') %></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to t('job.view'), jobs_path %></h5>
        <p class="card-text"><%= t('job.view_desc') %></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <% if can? :create, Job %>
            <%= link_to t('job.shared.add'), new_job_path %>
          <% end %>
        </h5>
        <p class="card-text"><%= t('job.shared.add_desc') %></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to t('candidate_job.application'), candidate_jobs_path %></h5>
        <p class="card-text"><%= t('candidate_job.application_desc') %></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to t('job.calendar.dead'), calendar_path %></h5>
        <p class="card-text"><%= t('job.calendar.view') %></p>
      </div>
    </div>
  </div>
</div>