config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'users#new', :as => 'register'

  get '/confirm_email/:token', to: 'email_confirmations#confirm', as: 'confirm_email'

  root 'pages#index'

  resources :users
  resources :pages
  resources :candidates
  resources :jobs do
    resources :candidate_jobs, except: %i(index show) do
    end
  end
  resources :admins
  resource  :help, only: %i(show)

  get '/candidate_jobs', controller: :candidate_jobs, action: :index
  get '/candidate_jobs/show/:job_id' => 'candidate_jobs#show', :as => :show_requests
  get '/jobs/calendars/show', as: 'calendar'
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :candidate_jobs
  has_many :candidates, through: :candidate_jobs

  scope :sorted_by_deadline, -> { order('deadline ASC') }
  validates :title, :description, presence: true

  def start_time
    deadline
  end
end

app/controllers/jobs/calendars_controller.rb
class Jobs::CalendarsController < ApplicationController
  def show
    return @calendars = current_user.candidate.candidate_jobs unless current_user.admin?

    @calendars = Job.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  load_and_authorize_resource

  def index
    @jobs = Job.sorted_by_deadline
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = t('job.notice_create')
      redirect_to jobs_path
    else
      flash.now[:error] = @job.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @job.update(job_params)
      flash[:notice] = t('job.notice_edit')
      redirect_to jobs_path
    else
      flash.now[:error] = @job.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @job.destroy
    flash[:notice] = t('job.notice_delete')
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:title,
                                :description,
                                :deadline)
  end
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :description, input_html: { id: 'wysiwyg' } %>
  <%= f.input :deadline, as: :date, html5: true %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/jobs/edit.html.erb
<div class="job-new">
  <div class="container">
    <h4><%= link_to t('job.shared.back'), jobs_path %></h4>
    <h2><%= t('job.shared.update') %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="job-index">
  <div class="container">
    <%= link_to t('job.shared.back_admin'), admins_path %>
    <h2><%= t('job.list') %></h2>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('job.position') %></th>
        <th><%= t('job.date_issued') %></th>
        <th><%= t('job.deadline') %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= raw(job.title) %></td>
          <td><%= job.created_at.strftime('%b %d, %Y') %></td>
          <td><%= job.deadline.strftime('%b %d, %Y') %></td>
          <td>
            <% if can? :read, Job %>
                <%= link_to t('shared.all.show'), job_path(job), class: 'btn btn-primary' %>
            <% end %>
            <% if can? :edit, Job %>
                <%= link_to t('shared.all.edit'), edit_job_path(job), class: 'btn btn-default' %>
            <% end %>
            <% if can? :delete, Job %>
                <%= link_to t('shared.all.delete'), job_path(job), class: 'btn btn-danger', method: :delete,
                            data: { confirm: t('shared.all.confirm_delete') } %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="job-new">
  <div class="container">
    <h4><%= link_to t('job.shared.back_admin'), admins_path %></h4>
    <h2><%= t('job.shared.new') %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="job-show">
  <div class="container">
    <% if current_user.admin? %>
      <h4><%= link_to t('job.shared.back'), jobs_path %></h4>
    <% else %>
      <h4><%= link_to t('shared.all.back'), candidate_jobs_path %></h4>
      <%= link_to t('job.apply'), new_job_candidate_job_path(job_id: @job.id) %>
    <% end %>
    <h2><%= t('job.details') %></h2>
    <br>
    <form>
      <div class="form-group">
        <label class="font-weight-bold"><%= t('job.title') %></label>
        <div><%= @job.title %></div>
      </div>
      <div class="form-group">
        <label class="font-weight-bold fr-view"><%= t('job.description') %></label>
        <div><%= @job.description.html_safe %></div>
      </div>
      <div class="form-group">
        <label class="font-weight-bold"><%= t('job.deadline') %></label>
        <div><%= @job.deadline %></div>
      </div>
    </form>
  </div>
</div>