config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'users#new', :as => 'register'

  get '/confirm_email/:token', to: 'email_confirmations#confirm', as: 'confirm_email'

  root 'pages#index'

  resources :users
  resources :pages
  resources :candidates
  resources :jobs do
    resources :candidate_jobs, except: %i(index show) do
    end
  end
  resources :admins
  resource  :help, only: %i(show)

  get '/candidate_jobs', controller: :candidate_jobs, action: :index
  get '/candidate_jobs/show/:job_id' => 'candidate_jobs#show', :as => :show_requests
  get '/jobs/calendars/show', as: 'calendar'
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_one_attached :avatar
  belongs_to :user
  has_many :candidate_jobs
  has_many :jobs, through: :candidate_jobs

  store_accessor :english_proficiency, :english_reading, :english_writing, :english_speaking
  store_accessor :bangla_proficiency, :bangla_reading, :bangla_writing, :bangla_speaking

  enum gender: { male: 0, female: 1 }

  scope :sorted_by_experience, -> { order('experience ASC') }

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :cgpa, :passing_year, presence: true
  validates :skill, :personal_interest, presence: true
  validates :experience, presence: true, numericality: true
  validates :contact, numericality: true
  validates :user_id, presence: true, uniqueness: true
  validates :dob, presence: true

  before_validation { avatar.delete if @delete_avatar }

  def delete_avatar
    @delete_avatar ||= false
  end

  def delete_avatar=(value)
    @delete_avatar  = value.to_i.nonzero?
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :check_if_email_confirmed
  skip_before_action :check_if_profile_filled?
  load_and_authorize_resource

  def index
    @candidates = Candidate.sorted_by_experience
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = current_user.build_candidate(candidate_params)
    @candidate.avatar.attach(candidate_params[:avatar])
    if @candidate.save
      flash[:notice] = t('candidate.notice_create', candidate_name: @candidate.name)
      redirect_to pages_path
    else
      flash.now[:error] = @candidate.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @candidate.update(candidate_params)
      flash[:notice] = t('candidate.notice_edit', candidate_name: @candidate.name)
      redirect_to pages_path
    else
      flash.now[:error] = @candidate.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @candidate.destroy
      flash[:notice] = t('candidate.notice_delete', candidate_name: @candidate.name)
      redirect_to candidates_path
    end
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name,
                                      :email,
                                      :contact,
                                      :gender,
                                      :address,
                                      :dob,
                                      :university_name,
                                      :major,
                                      :degree,
                                      :cgpa,
                                      :passing_year,
                                      :skill,
                                      :experience,
                                      :personal_interest,
                                      :long_term_plan,
                                      :hobbies,
                                      :keywords,
                                      :referrals,
                                      :avatar,
                                      :delete_avatar,
                                      :user_id,
                                      :english_writing,
                                      :english_reading,
                                      :english_speaking,
                                      :bangla_writing,
                                      :bangla_reading,
                                      :bangla_speaking,
                                      :award_certificate,
                                      :career_objective,
                                      :project_url)
  end

  def check_if_email_confirmed
    return unless current_user
    redirect_to sign_in_path if current_user.email_confirmed_at.blank?
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  require 'date'

  def human_attribute_genders
    Hash[Candidate.genders.map { |k,v| [k, Candidate.human_attribute_name("gender.#{k}")] }]
  end

  def age(dob)
    if valid_date = dob.try(:to_date)
      today = Date.today
      age = today.year - valid_date.year
      age -= 1 if valid_date.strftime('%m%d').to_i > today.strftime('%m%d').to_i
      age
    end
  end

  def valid_age?(dob)
    applicant_age = age(dob)
    applicant_age > 15
  end
end

app/views/candidates/_additionalinfo.html.erb
<%= f.input :hobbies, label: t('shared.all.hobby'), input_html: {rows: 3} %>
<%= f.input :personal_interest, input_html: {rows: 3} %>
<%= f.input :keywords %>
<%= f.input :referrals %>
<%= f.label :english_proficiency %>
<div class="english-language">
  <%= f.input :english_reading,
              collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.read') %>
  <%= f.input :english_writing,
              collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.write') %>
  <%= f.input :english_speaking,
              collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.speak') %>
</div>
<%= f.label :bangla_proficiency %>
<div class="english-language">
  <%= f.input :bangla_reading, collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.read') %>
  <%= f.input :bangla_writing, collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.write') %>
  <%= f.input :bangla_speaking, collection: [t('candidate.high'), t('candidate.medium'), t('candidate.low')], label: t('candidate.speak') %>
</div>
<%= f.input :other_language %>
<%= f.button :submit, t('candidate.add') %>

app/views/candidates/_education.html.erb
<%= f.input :university_name%>
<%= f.input :degree %>
<%= f.input :major%>
<%= f.input :cgpa%>
<%= f.input :passing_year%>
<%= f.input :award_certificate %>

app/views/candidates/_experience.html.erb
<%= f.input :skill, input_html: {rows: 3}, separator: ',' %>
<%= f.input :experience%>
<%= f.input :long_term_plan, input_html: {rows: 3} %>
<%= f.input :career_objective %>
<%= f.input :project_url %>
<% if @candidate.avatar.attached? && @candidate.avatar.blob_id? %>
  <%= f.label :avatar, label: t('shared.all.file_up') %><%= @candidate.avatar.filename %>
  <div class="checkbox_avatar">
    <%= f.check_box :delete_avatar %><p><%= t('shared.all.delete_file') %></p>
  </div>
<% else %>
  <%= f.input :avatar, label: t('shared.all.file_up'), as: :file %>
<% end %>

app/views/candidates/_form.html.erb
<%= f.error_notification %>
<%= f.input :name, input_html: { value: current_user.set_name } %>
<%= f.label :gender %>
<%= f.collection_radio_buttons :gender, human_attribute_genders,
                               :first,
                               :second,
                               checked: human_attribute_genders.first %>
<%= f.input :email, placeholder: t('simple_form.placeholders.candidate.email')%>
<%= f.input :address, input_html: {rows: 3} %>
<%= f.input :contact%>
<%= f.input :dob,
            as: :date,
            html5: true,
            :order => [ :day, :month, :year] %>

app/views/candidates/edit.html.erb
<div class ="candidate edit">
  <br />
  <%= link_to t('shared.all.back'), candidate_jobs_path %>

  <div class="help-link">
    <%= link_to image_tag('help_page_icon.png'), help_path %>
  </div>

  <div class="form-group">
    <div class="container">
      <h2><%= t('candidate.update') %></h2>
      <%= simple_form_for @candidate do |f| %>
        <input id='step2' type='checkbox'>
        <input id='step3' type='checkbox'>
          <input id='step4' type='checkbox'>
          <div id="part1" class="form-group">
            <h3><%= t('candidate.basic_info') %></h3>
            <%= render 'form', f: f %>
            <div class="nav_con_btn">
              <div>
                <label for='step2' id="continue-step2" class="continue">
                  <div class="btn-success"><%= t('shared.all.next') %></div>
                </label>
              </div>
            </div>
          </div>

          <div id="part2" class="form-group">
            <h3><%= t('candidate.edu_profile') %></h3>
            <%= render 'education', f: f %>
            <div class="nav_btn">
              <label for='step2' id="back-step2" class="back">
                <div class="btn-back"><%= t('shared.all.prev') %></div>
              </label>
              <div>
                <label for='step3' id="continue-step3" class="continue">
                  <div class="btn-success_both"><%= t('shared.all.next') %></div>
                </label>
              </div>
            </div>
          </div>

          <div id="part3" class="form-group">
            <h3><%= t('candidate.prof_exp') %></h3>
            <%= render 'experience', f: f %>
            <div class="nav_btn">
              <label for='step3' id="back-step3" class="back">
                <div class="btn-back"><%= t('shared.all.prev') %></div>
              </label>
              <div>
                <label for='step4' id="continue-step4" class="continue">
                  <div class="btn-success_both"><%= t('shared.all.next') %></div>
                </label>
              </div>
            </div>
          </div>

          <div id="part4" class="form-group">
            <h3><%= t('candidate.additional_info') %></h3>
            <%= render 'additionalinfo', f: f %>
            <div class="nav_back_btn">
              <div>
                <label for='step4' id="back-step4" class="back">
                  <div class="btn-back"><%= t('shared.all.prev') %></div>
                </label>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/candidates/index.html.erb
<div class="candidate index">
  <h2><%=t('candidate.candidate_list')%></h2>
  <%= link_to t('job.shared.back_admin'), admins_path %>
  <div class = "image">
    <% if can? :create, Candidate %>
    <%= link_to t('candidate.add'), new_candidate_path %>
    <% end %>
  </div>
  <br /><br />
  <table class="listing" summary="Candidate List">
    <tr class="header">
      <th class="center"><%=t('candidate.name')%></th>
      <th class="center"><%=t('shared.all.email')%></th>
      <th class="center"><%=t('shared.all.phone')%></th>
      <th class="center"><%=t('shared.all.exp')%></th>
      <th class="center"></th>
    </tr>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.contact %></td>
        <td><%= candidate.experience %></td>
        <td class="actions">
          <% if can? :read, Candidate %>
          <%= link_to t('shared.all.show'), candidate_path(candidate) %>
          <% end %>
          <% if can? :edit, Candidate %>
          <%= link_to t('shared.all.edit'), edit_candidate_path(candidate) %>
          <% end %>
          <% if can? :delete, Candidate %>
          <%= link_to t('shared.all.delete'), candidate_path(candidate), method: :delete,
                      data: {confirm: I18n.t('shared.all.confirm_delete')} %>
          <% end %>
        </td>
     </tr>
    <% end %>
    <%= paginate @candidates %>
  </table>
</div>

app/views/candidates/new.html.erb
<div class ="candidate new">
  <br />
  <%= link_to t('shared.all.back'), pages_path %>

  <div class="help-link">
    <%= link_to image_tag('help_page_icon.png'), help_path %>
  </div>

  <div class="form-group">
    <div class="container">
      <h2><%= t('candidate.new') %></h2>
      <h3><%= t('candidate.info') %></h3>
      <%= simple_form_for @candidate do |f| %>
        <input id='step2' type='checkbox'>
        <input id='step3' type='checkbox'>
        <input id='step4' type='checkbox'>
        <div id="part1" class="form-group">
          <h3><%= t('candidate.basic_info') %></h3>
            <%= render 'form', f: f %>
          <div class="nav_con_btn">
            <div>
              <label for='step2' id="continue-step2" class="continue">
                <div class="btn-success"><%= t('shared.all.next') %></div>
              </label>
            </div>
          </div>
        </div>

        <div id="part2" class="form-group">
          <h3><%= t('candidate.edu_profile') %></h3>
          <%= render 'education', f: f %>
          <div class="nav_btn">
            <label for='step2' id="back-step2" class="back">
              <div class="btn-back"><%= t('shared.all.prev') %></div>
            </label>
            <div>
              <label for='step3' id="continue-step3" class="continue">
                <div class="btn-success_both"><%= t('shared.all.next') %></div>
              </label>
            </div>
          </div>
        </div>

        <div id="part3" class="form-group">
          <h3><%= t('candidate.prof_exp') %></h3>
          <%= render 'experience', f: f %>
          <div class="nav_btn">
            <label for='step3' id="back-step3" class="back">
              <div class="btn-back"><%= t('shared.all.prev') %></div>
            </label>
            <div>
              <label for='step4' id="continue-step4" class="continue">
                <div class="btn-success_both"><%= t('shared.all.next') %></div>
              </label>
            </div>
          </div>
        </div>

        <div id="part4" class="form-group">
          <h3><%= t('candidate.additional_info') %></h3>
          <%= render 'additionalinfo', f: f %>
          <div class="nav_back_btn">
            <div>
              <label for='step4' id="back-step4" class="back">
                <div class="btn-back"><%= t('shared.all.prev') %></div>
              </label>
            </div>
          </div>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="candidate show">
  <br />
  <% if current_user.admin? %>
      <%= link_to t('shared.all.back'), candidates_path %>
  <% else %>
      <%= link_to t('shared.all.back'), candidate_jobs_path %>
  <% end %>
  <div class="card-show">
    <div class="container-show">
      <h2><%= t('candidate.details') %></h2>

      <div class="tab">
        <button class="tablinks" onclick="openCity(event,'Basic')"><%=t('candidate.basic_info')%></button>
        <button class="tablinks" onclick="openCity(event,'Educ')"><%= t('candidate.edu_profile') %></button>
        <button class="tablinks" onclick="openCity(event,'Prof')"><%= t('candidate.prof_exp') %></button>
        <button class="tablinks" onclick="openCity(event,'Additional')"><%= t('candidate.additional_info') %></button>
      </div>

      <div id="Basic" class="tabcontent">
        <h3><%= t('candidate.basic_info') %></h3>
        <table summary="School detail view">
          <tr>
            <th><%= t('candidate.name') %></th>
            <td><%= @candidate.name %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.email') %></th>
            <td><%= @candidate.email %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.phone') %></th>
            <td><%= @candidate.contact %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.gender') %></th>
            <td>
              <% if @candidate.gender == 'female' %>
                  <%= t('shared.all.female') %>
              <% else %>
                  <%= t('shared.all.male') %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= t('candidate.age') %></th>
            <% dob = @candidate.dob %>
            <td>
              <% if valid_age?(dob) %>
                <%= age(dob) %> <%= t('shared.all.years') %>
              <% else %>
                <%= t('candidate.inapproriate_dob') %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= t('shared.all.address') %></th>
            <td><%= @candidate.address %></td>
          </tr>
        </table>
      </div>

      <div id="Educ" class="tabcontent">
        <h3><%= t('candidate.edu_profile') %></h3>
        <table summary="School detail view">
          <tr>
            <th><%= t('candidate.uni_name') %></th>
            <td><%= @candidate.university_name %></td>
          </tr>
          <tr>
            <th><%= t('candidate.degree') %></th>
            <td><%= @candidate.degree %></td>
          </tr>
          <tr>
            <th><%= t('candidate.major') %></th>
            <td><%= @candidate.major %></td>
          </tr>
          <tr>
            <th><%= t('candidate.cgpa') %></th>
            <td><%= @candidate.cgpa %></td>
          </tr>
          <tr>
            <th><%= t('candidate.passing_year') %></th>
            <td><%= @candidate.passing_year %></td>
          </tr>
          <tr>
            <th><%= t('candidate.award') %></th>
            <td><%= @candidate.award_certificate %></td>
          </tr>
          <tr>
          </tr>
        </table>
      </div>

      <div id="Prof" class="tabcontent">
        <h3><%= t('candidate.prof_exp') %></h3>
        <table summary="School detail view">
          <tr>
            <th><%= t('shared.all.skill') %></th>
            <td><%= @candidate.skill.split(' ').join(',') %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.exp') %></th>
            <td><%= @candidate.experience %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.plan') %></th>
            <td><%= @candidate.long_term_plan %></td>
          </tr>
          <tr>
            <th><%= t('candidate.career') %></th>
            <td><%= @candidate.career_objective %></td>
          </tr>
          <tr>
            <th><%= t('candidate.project') %></th>
            <td><%= @candidate.project_url %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.file_up') %></th>
            <td>
              <% if @candidate.avatar.attached? && @candidate.avatar.blob_id? %>
                  <%= link_to @candidate.avatar.filename, @candidate.avatar, download: '' %>
              <% else %>
                  <%= t('shared.all.not_avail') %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>

      <div id="Additional" class="tabcontent">
        <h3><%= t('candidate.additional_info') %></h3>
        <table summary="School detail view">
          <tr>
            <th><%= t('shared.all.hobby') %></th>
            <td><%= @candidate.hobbies %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.personal_int') %></th>
            <td><%= @candidate.personal_interest %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.plan') %></th>
            <td><%= @candidate.long_term_plan %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.keyword') %></th>
            <td><%= @candidate.keywords %></td>
          </tr>
          <tr>
            <th><%= t('shared.all.refer') %></th>
            <td><%= @candidate.referrals %></td>
          </tr>
          <tr>
            <th> <%= t('candidate.english')%> </th>
            <td>
            <div class="english-show">
              <span> <%= t('candidate.read') %> </span> <%=@candidate.english_reading %>
              <span> <%= t('candidate.write') %> </span><%=@candidate.english_writing %>
              <span> <%= t('candidate.speak') %> </span> <%=@candidate.english_speaking %>
            </div>
            </td>
          </tr>
          <tr>
          <tr>
            <th> <%= t('candidate.bangla')%> </th>
            <td>
              <div class="english-show">
                <span> <%= t('candidate.read') %> </span> <%=@candidate.bangla_reading %>
                <span> <%= t('candidate.write') %> </span><%=@candidate.bangla_writing %>
                <span> <%= t('candidate.speak') %> </span> <%=@candidate.bangla_speaking %>
              </div>
            </td>
          </tr>
          <tr>
            <th> <%= t('candidate.other') %> </th>
            <td> <%= @candidate.other_language %> </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>