config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'users#new', :as => 'register'

  get '/confirm_email/:token', to: 'email_confirmations#confirm', as: 'confirm_email'

  root 'pages#index'

  resources :users
  resources :pages
  resources :candidates
  resources :jobs do
    resources :candidate_jobs, except: %i(index show) do
    end
  end
  resources :admins
  resource  :help, only: %i(show)

  get '/candidate_jobs', controller: :candidate_jobs, action: :index
  get '/candidate_jobs/show/:job_id' => 'candidate_jobs#show', :as => :show_requests
  get '/jobs/calendars/show', as: 'calendar'
end

app/models/candidate_job.rb
class CandidateJob < ApplicationRecord
  COLORS = { junior_software_engineer: 'junior-engineer',
             front_end_engineer: 'front-engineer',
             senior_software_engineer: 'senior-engineer' }
  belongs_to :candidate
  belongs_to :job

  validates :candidate_id, presence: true, uniqueness: { scope: :job_id }
  validates :job_id, presence: true
  validates :expected_salary, presence: true, numericality: true

  def job_applied?(candidateid, jobid)
    CandidateJob.exists?(candidate_id: candidateid, job_id: jobid)
  end

  def start_time
    created_at
  end

  def end_time
    Job.find(job_id).deadline
  end

  def title
    Job.find(job_id).title
  end
end

app/controllers/candidate_jobs_controller.rb
class CandidateJobsController < ApplicationController
  before_action :find_candidate
  load_and_authorize_resource :job, except: :index
  load_and_authorize_resource through: :job, except: :index

  def index
    @jobs = Job.sorted_by_deadline
  end

  def show
    @candidate_jobs = @job.candidate_jobs.page(params[:page])
    respond_to do |format|
      format.html
      format.json { render json: @candidate_jobs, people: @candidate_jobs }
    end
  end

  def new; end

  def create
    if @candidate_job.save
      flash[:notice] = t('job.applied')
      redirect_to candidate_jobs_path
    else
      flash.now[:error] = @candidate_job.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def candidate_job_params
    allowed_params = params.require(:candidate_job).permit(:expected_salary)
    allowed_params.merge(candidate_id: @candidate.id)
  end

  def find_candidate
    @candidate = current_user.candidate
  end
end

app/views/candidate_jobs/_results.html.erb
<table class="table table-hover" id="myTable"> 
  <thead> 
  <tr> 
    <th><%= t('candidate.applicant') %></th> 
    <th><%= t('candidate.uni_name') %></th> 
    <th><%= t('candidate.cgpa') %></th> 
    <th><%= t('shared.all.skill') %></th> 
    <th><%= t('candidate.prof_exp') %></th> 
    <th><%= t('candidate_job.expected_salary') %></th> 
    <th><%= t('shared.all.actions') %></th> 
  </tr> 
  </thead> 
  <tbody> 
  <% if @candidate_jobs %>
    <% @candidate_jobs.each do |candidate_job| %> 
    <tr> 
      <td><%= candidate_job.candidate.name %></td> 
      <td><%= candidate_job.candidate.university_name %></td> 
      <td class="cgpa-search"><%= candidate_job.candidate.cgpa %></td> 
      <td><%= candidate_job.candidate.skill %></td> 
      <td class="filter-column-exp"><%= candidate_job.candidate.experience %></td> 
      <td class="filter-column-salary"><%= candidate_job.expected_salary %></td> 
      <td class="actions"> 
        <%= link_to t('shared.all.show'), candidate_path(candidate_job.candidate) %> 
      </td> 
    </tr> 
    <% end %>
  <% end %>
  </tbody> 
  <%= paginate @candidate_jobs %> 
</table> 

app/views/candidate_jobs/index.html.erb
<% if current_user.applicant? %>
  <div class="candidatejob index applicant">
    <h2><%= t('candidate.welcome', candidate_name: current_user.candidate.name) %></h2>
    <% @candidate = current_user.candidate %>
    <% if current_user.candidate %>
    <div class="page_nav">
      <%= link_to t('candidate.view'), candidate_path(@candidate)%>  |
      <%= link_to t('candidate.edit'), edit_candidate_path(@candidate) %>  |
      <%= link_to t('job.calendar.dead'), calendar_path %>
    </div>
    <% end %>
    <h3><%= t('job.list') %></h3>
    <% @jobs.each do |job| %>
      <% if job.deadline >= Date.today %>
        <div class="card">
          <div class="card-header"><%= raw(job.title) %></div>
          <div class="card-body">
            <p class="card-text">
              <%= t('job.deadline') %>: <%= job.deadline.strftime('%b %d, %Y') %><br/>
              <%= link_to t('shared.all.show'), job_path(job), class: 'btn btn-primary' %>
              <% if CandidateJob.exists?(candidate_id: @candidate.id, job_id: job.id) %>
                  <%= t('job.already_apply') %>
              <% else %>
                  <% if can? :create, CandidateJob %>
                      <%= link_to t('job.apply'),
                                  new_job_candidate_job_path(job_id: job.id),
                                  class: 'btn btn-primary' %>
                  <% end %>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="candidatejob index admin">
    <h4><%= link_to t('job.shared.back_admin'), admins_path %></h4>
    <table class="listing">
      <tr class="header">
        <th class="center"><%=t('job.title')%></th>
        <th class="center"><%=t('candidate_job.number_applicants')%></th>
      </tr>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.candidates.size %></td>
          <td class="actions">
            <%= link_to t('candidate_job.view_applicants'), show_requests_path(job.id) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/candidate_jobs/new.html.erb
<div class="apply page">
  <%= link_to t('shared.all.back'), candidate_jobs_path %>
  <div class="form-group">
    <div class="container">
      <h2><%= t('shared.all.online_app') %></h2>
      <p><%= t('candidate.applicant') %>: <%= current_user.candidate.name %></p>
      <p><%= t('job.title') %>: <%= @job.title %></p>
      <%= simple_form_for @candidate_job, url: job_candidate_jobs_path do |f| %>
        <%= f.error_notification %>
        <%= f.input :expected_salary,
                    label: t('candidate_job.expected_salary'),
                    placeholder: t('candidate_job.currency') %>
          <% if @candidate_job.job_applied?(@candidate.id, @job.id) %>
              <%= f.button :submit, t('job.already_apply'), disabled: true %>
          <% else %>
              <%= f.button :submit, t('job.apply') %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/candidate_jobs/show.html.erb
<div class="show-request page">
  <div class="section alternate2-bg">
    <%= link_to t('shared.all.back'), candidate_jobs_path %> 
    <div id= "showname"> 
      <h2><%= @job.title %></h2> 
    </div>
    <%= simple_form_for :search, method: :get, html: { id: 'search-form' } do |form| %>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h4><%= t('shared.all.search_filter') %></h4>
          </div>
        </div>
      </div>
      <div class="section alternate2-bg">
        <div class="container ">
          <div class="row">
            <div class="col-md-12 ">
              <div class="">
                <input type="hidden" name="job_id" value="<%= @job.id %>" />
                <div class="form-group filter-group">
                  <%= form.input :skill, required: false, label: false, placeholder: 'Skill Search' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="container" id="search-results">
      <%= render '/candidate_jobs/results', people: [], xhr: true, candidate_jobs: @candidate_jobs %>
      <div class="no-results-msg alert alert-warning">
        <p>No result</p>
      </div>
    </div>
  </div>
</div>

app/views/candidate_jobs/show_requests.html.erb
<div class="show-request page">
  <br /><br />
  <%= link_to t('shared.all.back'), candidate_jobs_path %>
  <div id= "showname">
    <h2><%= @job.title %></h2>
  </div>
  <table class="table table-hover">
    <thead>
    <tr>
      <th><%= t('candidate.applicant') %></th>
      <th><%= t('candidate_job.expected_salary') %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @candidate_jobs.each do |candidate_job| %>
      <tr>
        <td><%= candidate_job.candidate.name %>
        <td><%= candidate_job.expected_salary %>
        </td>
        <td class="actions">
          <%= link_to t('shared.all.show'), candidate_path(candidate_job.candidate) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>